import {test,expect} from '@playwright/test';
import {localBoard} from './readOnlyBoard';
test('try on uses live content without saving; apply and grouped parts persist',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1920,height:1080});await page.goto('/new-shul.html');
 await expect(page.getByTestId('design-try-on')).toBeVisible();
 const data=await localBoard(page);data.tv_config[0].config.alerts={...data.tv_config[0].config.alerts,enabled:false};await localBoard(page,{tv_config:data.tv_config});await page.reload();
 const before=(await localBoard(page)).tv_config[0].config;
 const trial=page.getByTestId('design-try-on');
 await trial.getByLabel('ערכה לניסיון').selectOption('d_salonivory');
 const preview=page.locator('[data-board-preview]').first();
 await expect(preview.locator('[data-element-id="salonivory_prayers_content"]')).toContainText('שחרית');
 expect((await localBoard(page)).tv_config[0].config).toEqual(before);
 await preview.screenshot({path:'../outputs/design-try-on-preview.png'});
 await expect(page.getByRole('button',{name:'שמירה מקומית',exact:true}).first()).toBeDisabled();
 await trial.getByRole('button',{name:'הצגת העיצוב הנוכחי',exact:true}).click();
 await expect(preview.locator('[data-element-id="salonivory_prayers_content"]')).toHaveCount(0);
 await trial.getByRole('button',{name:'הצגת הערכה לניסיון',exact:true}).click();
 await expect(preview.locator('[data-element-id="salonivory_prayers_content"]')).toContainText('שחרית');
 await trial.getByRole('button',{name:'החלה לטיוטה',exact:true}).click();
 await page.getByRole('button',{name:'שמירה מקומית',exact:true}).first().click();
 await expect(page.getByRole('button',{name:'שמירה מקומית',exact:true}).first()).toBeDisabled();await page.reload();
 const baseline=(await localBoard(page)).tv_config[0].config.elements;
 expect(baseline.some(e=>e.id==='salonivory_prayers_content')).toBe(true);
 await page.getByRole('tab',{name:'פריסה',exact:true}).click();
 const combos=page.getByTestId('combination-library');await expect(combos.getByRole('button')).toHaveCount(6);
 await combos.getByRole('button',{name:'הוספת שילוב פינת תפילות',exact:true}).click();
 await page.getByRole('button',{name:'שמירה מקומית',exact:true}).first().click();await expect(page.getByRole('button',{name:'שמירה מקומית',exact:true}).first()).toBeDisabled();await page.reload();
 const after=(await localBoard(page)).tv_config[0].config.elements;
 expect(after.slice(0,baseline.length)).toEqual(baseline);
 const added=after.slice(baseline.length);expect(added).toHaveLength(4);
 expect(new Set(added.map(e=>e.group)).size).toBe(1);expect(added[0].group).toBeTruthy();expect(added.find(e=>e.binding==='prayers')).toBeTruthy();
 expect(new Set(after.map(e=>e.id)).size).toBe(after.length);
 expect(errors).toEqual([]);
});
