import { test, expect } from '@playwright/test';
import { readFile, writeFile } from 'node:fs/promises';
import JSZip from 'jszip';

test('New Shul original site-data JSON and Excel import update local records without duplicates', async ({page},info) => {
  test.skip(info.project.name!=='desktop-chromium','Data formats tested once');
  await page.goto('/new-shul.html');
  await page.getByRole('button',{name:'ייבוא / ייצוא',exact:true}).first().click();
  const section = page.getByTestId('site-data-transfer');
  await section.locator('summary').click();
  const download = page.waitForEvent('download');
  await section.getByRole('button',{name:'ייצוא ל-JSON',exact:true}).click();
  const data = JSON.parse(await readFile((await (await download).path())!,'utf8'));
  expect(data.source).toBe('shul-hub');
  expect(data.tables.settings).toHaveLength(1);
  expect(data.tables.minyanim).toHaveLength(3);
  expect(data.tables.tv_config).toBeUndefined();
  data.tables.minyanim[0].label='שחרית בדיקת ייבוא';
  await section.locator('input[type=file]').setInputFiles({name:'site.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});
  await page.getByRole('button',{name:'אישור ייבוא',exact:true}).click();
  await expect(page.getByText(/יובאו \d+ רשומות בהצלחה/)).toBeVisible();
  const excel = page.waitForEvent('download');
  await section.getByRole('button',{name:'ייצוא ל-Excel',exact:true}).click();
  const workbook = await readFile((await (await excel).path())!);
  await section.locator('input[type=file]').setInputFiles({name:'site.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:workbook});
  await page.getByRole('button',{name:'אישור ייבוא',exact:true}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.reload();
  await page.getByRole('button',{name:'ייבוא / ייצוא',exact:true}).first().click();
  await section.locator('summary').click();
  const verify = page.waitForEvent('download');
  await section.getByRole('button',{name:'ייצוא ל-JSON',exact:true}).click();
  const restored = JSON.parse(await readFile((await (await verify).path())!,'utf8'));
  expect(restored.tables.settings).toHaveLength(1);
  expect(restored.tables.minyanim).toHaveLength(3);
  expect(restored.tables.minyanim[0].label).toBe('שחרית בדיקת ייבוא');
});

test('New Shul transfer shortcut and original format round trip', async ({page}) => {
  await page.goto('/new-shul.html');
  await page.getByRole('button',{name:'ייבוא / ייצוא',exact:true}).first().click();
  const section = page.getByTestId('board-transfer-section');
  await expect(section.getByRole('heading',{name:'ייבוא וייצוא',exact:true})).toBeFocused();
  await section.locator('input[type=file][accept="application/json,.json"]').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'design-tokens',version:1,themes:[],gradients:[{name:'בדיקת מעבר מקורית',value:'linear-gradient(90deg, #123456, #abcdef)'}]}))});
  await expect(page.getByText(/יובאו 1 גרדיאנטים/)).toBeVisible();
  const wait = page.waitForEvent('download');
  await section.getByRole('button',{name:'צבעים ומבנה בסיסי (JSON)',exact:true}).click();
  const bytes = await readFile((await (await wait).path())!);
  const file = JSON.parse(bytes.toString());
  expect(file.format).toBe('design-tokens');
  expect(file.gradients[0].value).toBe('linear-gradient(90deg, #123456, #abcdef)');
  expect(file.elements).toBeUndefined();
  await section.locator('input[type=file][accept="application/json,.json"]').setInputFiles({name:'roundtrip.json',mimeType:'application/json',buffer:bytes});
  await page.getByRole('button',{name:'שמירה מקומית',exact:true}).first().click();
  await expect(page.getByRole('button',{name:'שמירה מקומית',exact:true}).first()).toBeDisabled();
  await page.reload();
  await page.getByRole('button',{name:'ייבוא / ייצוא',exact:true}).first().click();
  const again = page.waitForEvent('download');
  await section.getByRole('button',{name:'צבעים ומבנה בסיסי (JSON)',exact:true}).click();
  const restored = JSON.parse(await readFile((await (await again).path())!,'utf8'));
  expect(restored.gradients.map((g:{name:string})=>g.name)).toEqual(['בדיקת מעבר מקורית','בדיקת מעבר מקורית (2)']);
});

test('New Shul portable artwork ZIP imports in a fresh workspace without bundled art files', async ({page,browser},info) => {
  test.skip(info.project.name!=='desktop-chromium','Full board visual audit uses desktop viewport');
  test.setTimeout(120000);
  await page.setViewportSize({width:1920,height:1080});
  await page.goto('/new-shul.html');
  await page.getByRole('tab',{name:'עיצוב',exact:true}).click();
  await page.getByTestId('builtin-designs').getByRole('button',{name:/^ארמון אמרלד/}).click();
  const editor = page.getByTestId('elements-editor');
  await expect(page.getByTestId('artwork-layer-disclosure')).toBeVisible();
  const board = page.locator('.tv-root').first();
  await board.screenshot({path:'../outputs/new-shul-audit-before.png'});
  const textBefore = await board.getByText('שבת שלום',{exact:true}).evaluate(e=>e.parentElement!.getAttribute('style'));
  await editor.getByRole('button',{name:'הסתרת מסגרת תפילות',exact:true}).click();
  await expect(board.locator('img[alt="מסגרת תפילות"]')).not.toBeVisible();
  expect(await board.getByText('שבת שלום',{exact:true}).evaluate(e=>e.parentElement!.getAttribute('style'))).toEqual(textBefore);
  await board.screenshot({path:'../outputs/new-shul-audit-hidden-crop.png'});
  await editor.getByRole('button',{name:'הצגת מסגרת תפילות',exact:true}).click();
  await editor.getByLabel('שכבות האלמנטים').getByRole('button',{name:'ברכת קבלת פנים',exact:true}).click();
  await editor.getByLabel('תוכן האלמנט',{exact:true}).fill('טקסט נפרד שעבר בין סביבות');
  await page.getByRole('button',{name:'ייבוא / ייצוא',exact:true}).first().click();
  const wait = page.waitForEvent('download');
  await page.getByRole('button',{name:'ייצוא חבילת ZIP',exact:true}).click();
  const bytes = await readFile((await (await wait).path())!);
  await writeFile('../outputs/new-shul-audit-portable.zip',bytes);
  const zip = await JSZip.loadAsync(bytes);
  const doc = JSON.parse(await zip.file('board.json')!.async('string'));
  expect(doc.version).toBe(2);
  expect(Object.keys(doc.assets)).toHaveLength(1);
  expect(Object.keys(zip.files).filter(x=>/^assets\/\d/.test(x))).toHaveLength(1);
  const fresh = await browser.newContext({viewport:{width:1920,height:1080}});
  try {
    const target = await fresh.newPage();
    const errors:string[]=[]; target.on('pageerror',e=>errors.push(e.message));
    await target.route('**/new-shul-assets/**',r=>r.abort());
    await target.goto('http://127.0.0.1:4300/new-shul.html');
    await target.getByRole('button',{name:'ייבוא / ייצוא',exact:true}).first().click();
    const broken = await JSZip.loadAsync(bytes);
    broken.remove((Object.values(doc.assets)[0] as {file:string}).file);
    await target.getByLabel('ייבוא חבילת לוח').setInputFiles({name:'broken.zip',mimeType:'application/zip',buffer:await broken.generateAsync({type:'nodebuffer'})});
    await expect(target.getByText('תמונה חסרה בחבילה',{exact:true})).toBeVisible();
    await expect(target.getByRole('button',{name:'החלת הלוח המיובא',exact:true})).toHaveCount(0);
    await target.getByLabel('ייבוא חבילת לוח').setInputFiles({name:'portable.zip',mimeType:'application/zip',buffer:bytes});
    await target.getByRole('button',{name:'החלת הלוח המיובא',exact:true}).click();
    await expect(target.locator('.tv-root').getByText('טקסט נפרד שעבר בין סביבות',{exact:true})).toBeVisible();
    const art = target.locator('.tv-root img');
    await expect(art).toHaveCount(8);
    expect(await art.evaluateAll(imgs=>imgs.every(i=>i.getAttribute('src')?.startsWith('data:image/png;base64,')))).toBe(true);
    await target.getByRole('button',{name:'שמירה מקומית',exact:true}).first().click();
    await expect(target.getByRole('button',{name:'שמירה מקומית',exact:true}).first()).toBeDisabled();
    await target.goto('http://127.0.0.1:4300/new-shul.html?display=1');
    await expect(target.locator('.tv-root').getByText('טקסט נפרד שעבר בין סביבות',{exact:true})).toBeVisible();
    await expect.poll(()=>target.locator('.tv-root img').evaluateAll(imgs=>imgs.every(i=>(i as HTMLImageElement).complete && (i as HTMLImageElement).naturalWidth>0))).toBe(true);
    await target.screenshot({path:'../outputs/new-shul-audit-imported.png'});
    expect(errors).toEqual([]);
  } finally { await fresh.close(); }
});
