import {test,expect} from '@playwright/test';
import {localBoard} from './readOnlyBoard';

test('ready catalogue filters adds independent copies persists and exports all one hundred library parts',async({page,isMobile})=>{
 test.setTimeout(60000);
 if(!isMobile)await page.setViewportSize({width:1920,height:1080});
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/new-shul.html');
 await page.getByTestId('builtin-designs').getByRole('button',{name:/^תכלת גאומטרי · חלקים עצמאיים/}).click();
 await page.getByRole('button',{name:'שמירה מקומית',exact:true}).first().click();
 await expect(page.getByRole('button',{name:'שמירה מקומית',exact:true}).first()).toBeDisabled({timeout:20000});
 await page.getByRole('tab',{name:'פריסה',exact:true}).click();
 const library=page.getByTestId('element-library'),ready=page.getByTestId('ready-elements');
 await expect(ready.getByRole('button')).toHaveCount(60);
 await library.getByLabel('סוג אלמנטים מוכנים').selectOption('הכול');
 await expect(ready.getByRole('button')).toHaveCount(103);
 await library.getByLabel('סוג אלמנטים מוכנים').selectOption('שבת וחגים');
 await expect(ready.getByRole('button')).toHaveCount(16);
 await library.getByLabel('סוג אלמנטים מוכנים').selectOption('ריאליסטיים');
 await library.getByLabel('חיפוש אלמנטים מוכנים').fill('ספר לימוד פתוח על מעמד עץ');
 await expect(ready.getByRole('button')).toHaveCount(1);
 const initial=(await localBoard(page)).tv_config[0].config.elements.length;
 await ready.getByRole('button',{name:'הוספת ספר לימוד פתוח על מעמד עץ המוכן',exact:true}).click();
 await ready.getByRole('button',{name:'הוספת ספר לימוד פתוח על מעמד עץ המוכן',exact:true}).click();
 const editor=page.getByTestId('elements-editor');
 await editor.getByLabel('מיקום אופקי',{exact:true}).fill('65');
 await page.getByRole('button',{name:'שמירה מקומית',exact:true}).first().click();
 await expect(page.getByRole('button',{name:'שמירה מקומית',exact:true}).first()).toBeDisabled({timeout:20000});
 await page.reload();
 const config=(await localBoard(page)).tv_config[0].config;
 expect(config.elements).toHaveLength(initial+2);
 const copies=config.elements.filter((e:any)=>e.name==='ספר לימוד פתוח על מעמד עץ');
 expect(copies).toHaveLength(2);expect(new Set(copies.map((e:any)=>e.id)).size).toBe(2);
 expect(copies.map((e:any)=>e.x)).toEqual([38,65]);
 await page.getByRole('tab',{name:'פריסה',exact:true}).click();
 const download=page.waitForEvent('download');
 await library.getByRole('button',{name:'ייצוא ספריית האלמנטים',exact:true}).click();
 await (await download).saveAs('../outputs/new-shul-ready-elements.zip');
 await page.getByRole('button',{name:'ייבוא / ייצוא',exact:true}).first().click();
 await page.getByLabel('ייבוא חבילת לוח',{exact:true}).setInputFiles('../outputs/new-shul-ready-elements.zip');
 await page.getByRole('button',{name:'החלת הלוח המיובא',exact:true}).click();
 await page.getByRole('button',{name:'שמירה מקומית',exact:true}).first().click();
 await expect(page.getByRole('button',{name:'שמירה מקומית',exact:true}).first()).toBeDisabled({timeout:20000});
 await page.reload();
 const restored=(await localBoard(page)).tv_config[0].config;
 expect(restored.elements).toHaveLength(80);
 expect(restored.elementLibrary).toHaveLength(6);
 expect(restored.elementLibrary.flatMap((s:any)=>s.elements)).toHaveLength(103);
 await page.goto('/new-shul.html?display=1');
 await expect(page.locator('.tv-root [data-element-id]')).toHaveCount(80,{timeout:20000});
 await page.evaluate(async()=>{await Promise.all([...document.querySelectorAll('.tv-root img')].map(e=>(e as HTMLImageElement).decode()));});
 await page.screenshot({path:`../outputs/ready-elements-${isMobile?'mobile':'sheet'}.png`});
 expect(errors).toEqual([]);
});
