import { LOCAL_STUDIO, localFetch } from "@/newShul/localStore";
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { assertShulHubSupabase } from './project-boundary';
import { authSessionStorage } from '@/lib/authPreferences';

const SUPABASE_URL = LOCAL_STUDIO ? "http://127.0.0.1:9" : import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = LOCAL_STUDIO ? "new-shul-local-no-cloud" : import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!LOCAL_STUDIO) assertShulHubSupabase(SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: { fetch: LOCAL_STUDIO ? localFetch : (input, init) => {
    const headers = new Headers(input instanceof Request ? input.headers : undefined);
    new Headers(init?.headers).forEach((v,k)=>headers.set(k,v));
    if (SUPABASE_PUBLISHABLE_KEY.startsWith('sb_publishable_') && headers.get('Authorization') === `Bearer ${SUPABASE_PUBLISHABLE_KEY}`) headers.delete('Authorization');
    return fetch(input, {...init, headers});
  } },
  auth: {
    storage: authSessionStorage,
    persistSession: !LOCAL_STUDIO,
    autoRefreshToken: !LOCAL_STUDIO,
    detectSessionInUrl: !LOCAL_STUDIO,
  }
});
